apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8sdemo-integration-volume
  labels:
    type: local
spec:
  storageClassName: k8sdemo-integration-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8sdemo/integration/config"