apiVersion: v1
kind: Service
metadata:
  labels:
    env: k8sdemo-integration
  name: k8sdemo-integration
spec:
  ports:
    - nodePort: 31120
      port: 9120
      protocol: TCP
      targetPort: 9120
  selector:
    env: k8sdemo-integration
  type: NodePort