apiVersion: v1
kind: Pod
metadata:
  labels:
    env: k8sdemo-integration
  name: k8sdemo-integration
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: k8sdemo-integration-pvc
  containers:
    - name: k8sdemo-integration
      image: docker.io/library/k8sdemo-integration:v1.0.0
      volumeMounts:
        - mountPath: "/config"
          name: pv-storage
